name: Build and Upload Exploit

on:
  push:
    branches:
      - main  

jobs:
  build-and-upload:
    runs-on: ubuntu-20.04  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libmnl-dev libnftnl-dev gcc

      - name: Build exploit
        run: gcc exploit.c -o exploit -lmnl -lnftnl -no-pie -lpthread -D_DEFAULT_SOURCE

      - name: Upload to bashupload.com
        run: |
          URL=$(curl -s --upload-file ./exploit https://bashupload.com/exploit)
          echo "Uploaded to: $URL"
